name: Deploy to Portainer

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Portainer deployment
        run: |
          curl -X POST "${{ secrets.PORTAINER_WEBHOOK_URL }}"